FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src
COPY src ./src

RUN dotnet restore src/Project.HttpServer/Project.HttpServer.csproj
RUN dotnet publish src/Project.HttpServer/Project.HttpServer.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "Project.HttpServer.dll"]
